/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegistrerenRouteImport } from './routes/_auth/registreren'
import { Route as AuthWachtwoordVergetenRouteImport } from './routes/_auth/wachtwoord-vergeten'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicVerbodenGoederenRouteImport } from './routes/_public/verboden-goederen'
import { Route as PublicVoorwaardenRouteImport } from './routes/_public/voorwaarden'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalProfielRouteImport } from './routes/portal/profiel'
import { Route as AuthAuthConfirmRouteImport } from './routes/_auth/auth/confirm'
import { Route as AuthAuthSetPasswordRouteImport } from './routes/_auth/auth/set-password'
import { Route as PortalOrdersIndexRouteImport } from './routes/portal/orders/index'
import { Route as PortalOrdersIdRouteImport } from './routes/portal/orders/$id'
import { Route as PortalOrdersNieuwRouteImport } from './routes/portal/orders/nieuw'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegistrerenRoute = AuthRegistrerenRouteImport.update({
  id: '/registreren',
  path: '/registreren',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWachtwoordVergetenRoute = AuthWachtwoordVergetenRouteImport.update({
  id: '/wachtwoord-vergeten',
  path: '/wachtwoord-vergeten',
  getParentRoute: () => AuthRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicVerbodenGoederenRoute = PublicVerbodenGoederenRouteImport.update({
  id: '/verboden-goederen',
  path: '/verboden-goederen',
  getParentRoute: () => PublicRoute,
} as any)
const PublicVoorwaardenRoute = PublicVoorwaardenRouteImport.update({
  id: '/voorwaarden',
  path: '/voorwaarden',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalProfielRoute = PortalProfielRouteImport.update({
  id: '/profiel',
  path: '/profiel',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AuthAuthConfirmRoute = AuthAuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthSetPasswordRoute = AuthAuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => AuthRoute,
} as any)
const PortalOrdersIndexRoute = PortalOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalOrdersIdRoute = PortalOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalOrdersNieuwRoute = PortalOrdersNieuwRouteImport.update({
  id: '/orders/nieuw',
  path: '/orders/nieuw',
  getParentRoute: () => PortalRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/login': typeof AuthLoginRoute
  '/registreren': typeof AuthRegistrerenRoute
  '/wachtwoord-vergeten': typeof AuthWachtwoordVergetenRoute
  '/verboden-goederen': typeof PublicVerbodenGoederenRoute
  '/voorwaarden': typeof PublicVoorwaardenRoute
  '/portal/profiel': typeof PortalProfielRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/auth/confirm': typeof AuthAuthConfirmRoute
  '/auth/set-password': typeof AuthAuthSetPasswordRoute
  '/portal/orders/$id': typeof PortalOrdersIdRoute
  '/portal/orders/nieuw': typeof PortalOrdersNieuwRoute
  '/portal/orders/': typeof PortalOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof AuthLoginRoute
  '/registreren': typeof AuthRegistrerenRoute
  '/wachtwoord-vergeten': typeof AuthWachtwoordVergetenRoute
  '/verboden-goederen': typeof PublicVerbodenGoederenRoute
  '/voorwaarden': typeof PublicVoorwaardenRoute
  '/portal/profiel': typeof PortalProfielRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/auth/confirm': typeof AuthAuthConfirmRoute
  '/auth/set-password': typeof AuthAuthSetPasswordRoute
  '/portal/orders/$id': typeof PortalOrdersIdRoute
  '/portal/orders/nieuw': typeof PortalOrdersNieuwRoute
  '/portal/orders': typeof PortalOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/registreren': typeof AuthRegistrerenRoute
  '/_auth/wachtwoord-vergeten': typeof AuthWachtwoordVergetenRoute
  '/_public/verboden-goederen': typeof PublicVerbodenGoederenRoute
  '/_public/voorwaarden': typeof PublicVoorwaardenRoute
  '/portal/profiel': typeof PortalProfielRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_auth/auth/confirm': typeof AuthAuthConfirmRoute
  '/_auth/auth/set-password': typeof AuthAuthSetPasswordRoute
  '/portal/orders/$id': typeof PortalOrdersIdRoute
  '/portal/orders/nieuw': typeof PortalOrdersNieuwRoute
  '/portal/orders/': typeof PortalOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/portal'
    | '/'
    | '/login'
    | '/registreren'
    | '/wachtwoord-vergeten'
    | '/verboden-goederen'
    | '/voorwaarden'
    | '/portal/profiel'
    | '/admin/'
    | '/portal/'
    | '/auth/confirm'
    | '/auth/set-password'
    | '/portal/orders/$id'
    | '/portal/orders/nieuw'
    | '/portal/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/registreren'
    | '/wachtwoord-vergeten'
    | '/verboden-goederen'
    | '/voorwaarden'
    | '/portal/profiel'
    | '/admin'
    | '/portal'
    | '/auth/confirm'
    | '/auth/set-password'
    | '/portal/orders/$id'
    | '/portal/orders/nieuw'
    | '/portal/orders'
  id:
    | '__root__'
    | '/admin'
    | '/portal'
    | '/_auth'
    | '/_public'
    | '/_auth/login'
    | '/_auth/registreren'
    | '/_auth/wachtwoord-vergeten'
    | '/_public/verboden-goederen'
    | '/_public/voorwaarden'
    | '/portal/profiel'
    | '/_public/'
    | '/admin/'
    | '/portal/'
    | '/_auth/auth/confirm'
    | '/_auth/auth/set-password'
    | '/portal/orders/$id'
    | '/portal/orders/nieuw'
    | '/portal/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/registreren': {
      id: '/_auth/registreren'
      path: '/registreren'
      fullPath: '/registreren'
      preLoaderRoute: typeof AuthRegistrerenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/wachtwoord-vergeten': {
      id: '/_auth/wachtwoord-vergeten'
      path: '/wachtwoord-vergeten'
      fullPath: '/wachtwoord-vergeten'
      preLoaderRoute: typeof AuthWachtwoordVergetenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/verboden-goederen': {
      id: '/_public/verboden-goederen'
      path: '/verboden-goederen'
      fullPath: '/verboden-goederen'
      preLoaderRoute: typeof PublicVerbodenGoederenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/voorwaarden': {
      id: '/_public/voorwaarden'
      path: '/voorwaarden'
      fullPath: '/voorwaarden'
      preLoaderRoute: typeof PublicVoorwaardenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/profiel': {
      id: '/portal/profiel'
      path: '/profiel'
      fullPath: '/portal/profiel'
      preLoaderRoute: typeof PortalProfielRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_auth/auth/confirm': {
      id: '/_auth/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthAuthConfirmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/set-password': {
      id: '/_auth/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthAuthSetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/portal/orders/': {
      id: '/portal/orders/'
      path: '/orders'
      fullPath: '/portal/orders/'
      preLoaderRoute: typeof PortalOrdersIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/orders/$id': {
      id: '/portal/orders/$id'
      path: '/orders/$id'
      fullPath: '/portal/orders/$id'
      preLoaderRoute: typeof PortalOrdersIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/orders/nieuw': {
      id: '/portal/orders/nieuw'
      path: '/orders/nieuw'
      fullPath: '/portal/orders/nieuw'
      preLoaderRoute: typeof PortalOrdersNieuwRouteImport
      parentRoute: typeof PortalRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalProfielRoute: typeof PortalProfielRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalOrdersIdRoute: typeof PortalOrdersIdRoute
  PortalOrdersNieuwRoute: typeof PortalOrdersNieuwRoute
  PortalOrdersIndexRoute: typeof PortalOrdersIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalProfielRoute: PortalProfielRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalOrdersIdRoute: PortalOrdersIdRoute,
  PortalOrdersNieuwRoute: PortalOrdersNieuwRoute,
  PortalOrdersIndexRoute: PortalOrdersIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegistrerenRoute: typeof AuthRegistrerenRoute
  AuthWachtwoordVergetenRoute: typeof AuthWachtwoordVergetenRoute
  AuthAuthConfirmRoute: typeof AuthAuthConfirmRoute
  AuthAuthSetPasswordRoute: typeof AuthAuthSetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegistrerenRoute: AuthRegistrerenRoute,
  AuthWachtwoordVergetenRoute: AuthWachtwoordVergetenRoute,
  AuthAuthConfirmRoute: AuthAuthConfirmRoute,
  AuthAuthSetPasswordRoute: AuthAuthSetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicVerbodenGoederenRoute: typeof PublicVerbodenGoederenRoute
  PublicVoorwaardenRoute: typeof PublicVoorwaardenRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicVerbodenGoederenRoute: PublicVerbodenGoederenRoute,
  PublicVoorwaardenRoute: PublicVoorwaardenRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
